### ISSUE TITLE
Firebase Setup not Working

### ISSUE THREAD

**Issue by thebootlegboy** [MarmisDev/proxy#3]
Can you please tell us how to setup firebase login system ?

**Comment by marmisdev** [comment]
> 
> 
> Can you please tell us how to setup firebase login system ?

please check readme.

**Comment by thebootlegboy** [comment]
not mentioned any option about setup

i want the code and setup help 
it possible to get ?

**Comment by marmisdev** [comment]
Sorry, the source code is not available at this time.
